name: Bug Report
description: Create a report to help us improve
title: "[Bug] "
body:
  - type: markdown
    attributes:
      value: |
        *Please note: At the time being, only bug reports from Pixel Stock firmware, or Pixel Experience will be considered. Bug reports from other firmwares will only be taken into account if also reported from one of the supported roms.*
- type: textarea
- id: steps
  attributes:
    label: Steps to reproduce
    description: "How often do you or others encounter this bug?"
    placeholder: "Whenever I visit the user account page (1-2 times a week)"
  validations:
    required: true
