# This is a basic workflow to help you get started with Actions

name: testvrsion

# Controls when the workflow will run
on:
  push:
    tags: 
      '*'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        
    - name: Grant permission shell scripts
      run: chmod +x .github/*.sh
      
    - name: Update Versions
      run: .github/bumpVersion.sh

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        draft: true
        files: |
            app/build.gradle
