# This is a basic workflow to help you get started with Actions

name: testvrsion

# Controls when the workflow will run
on:
  push:
    tags: 
      '*'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        
    - name: Grant permission shell scripts
      run: chmod +x .github/*.sh
      
    - name: Update Versions
      run: .github/bumpVersion.sh

    - name: push
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'version bump'
        force-add: 'true'
        files: MagiskMod/module.prop app/build.gradle
        name: GitHub
        email: aospmods@siava.sh 
