# This is a basic workflow to help you get started with Actions

name: ZipMake

# Controls when the workflow will run
on:
  push
  
jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set Permissions
        run: chmod +x .github/make_zip.sh
        
      - name: Run the zip script
        run: .github/make_zip.sh
        
      - name: upload
        uses: actions/upload-artifact@v2
        with: 
          name: AOSPMods.zip
          path: /AOSPMods.zip
