# This is a basic workflow to help you get started with Actions

name: ZipMake

# Controls when the workflow will run
on:
  push
  
jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

    # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd MagiskMod,
          zip -r ../AOSPMods.zip *.
          
          
      - name: upload
        uses: actions/upload-artifact@v2
        with: 
          name: AOSPMods.zip
          path: /AOSPMods.zip
          
