name: Test Telegram

on:
  workflow_dispatch
      
jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - name: send telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.AOSPMODS_CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            this is a test message!
