name: test release action

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: make asset
        run: |
          mkdir output
          echo content > output/newasset.zip

      - name: Test Release
        uses: ncipollo/release-action@v1.13.0
        with:
          tag: 'test_tag'
          name: "test title from action"
          omitBodyDuringUpdate: true
          prerelease: true
          allowUpdates: true
          replacesArtifacts: true
          draft: true
          artifacts: 'output/*.*'