name: Test changelog

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    
    - name: Grab Source
      run: git clone --recurse-submodules https://github.com/siavash79/AOSPMods.git
      
    - name: Enter Repo
      run: cd AOSPMods
             
    - name: Grant permission shell scripts
      run: chmod +x .github/*.sh

    - name: Create Changelog
      run: .github/extractChanges.sh

    - name: Update Versions
      run: .github/bumpVersion.sh ${{ github.run_id }}

    - name: Commit version bump
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'canary'
        commit-message: 'test commit'
        force-add: 'true'
        files: CanaryChangelog.md
        name: GitHub
        email: aospmods@siava.sh
